project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p80/
  title: ""
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p80/
  navbar:
    logo: IQB-Klein.png
    search: true
    left:
        - text: ""
          href: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
